# Generated by Django 2.2.5 on 2020-08-11 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='patients/%y/%m/%d')),
                ('first_name', models.CharField(max_length=90)),
                ('last_name', models.CharField(max_length=90)),
                ('slug', models.SlugField(max_length=180)),
                ('address', models.CharField(max_length=90)),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (-1, 'Female'), (0, 'Other')])),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.SmallIntegerField(choices=[(1, 'O'), (2, 'A'), (3, 'AB'), (4, 'A')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
